# Generated by Django 5.2.4 on 2025-07-12 13:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del producto')),
                ('codigo_producto', models.CharField(max_length=50, unique=True, verbose_name='Código del producto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('combustible', 'Combustible'), ('lubricante', 'Lubricante'), ('aditivo', 'Aditivo'), ('servicio', 'Servicio'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría')),
                ('unit_of_measure', models.CharField(default='litros', max_length=50, verbose_name='Unidad de medida')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio base')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de venta')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Stock mínimo')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Stock actual')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
    ]
