# Generated by Django 5.2.4 on 2025-07-12 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del reporte')),
                ('tipo', models.CharField(choices=[('ventas', 'Reporte de Ventas'), ('clientes', 'Reporte de Clientes'), ('productos', 'Reporte de Productos'), ('sucursales', 'Reporte de Sucursales'), ('metas', 'Reporte de Metas'), ('ai_forecast', 'Reporte de Pronósticos IA'), ('custom', 'Reporte Personalizado')], max_length=20, verbose_name='Tipo de reporte')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='Parámetros del reporte')),
                ('datos', models.JSONField(blank=True, default=dict, verbose_name='Datos del reporte')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/', verbose_name='Archivo del reporte')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_generacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
