# Generated by Django 5.2.4 on 2025-07-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True, verbose_name='Clave de configuración')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Configuración activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'ordering': ['clave'],
            },
        ),
    ]
