# Generated by Django 5.2.4 on 2025-07-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro')], default='light', max_length=10, verbose_name='Preferencia de tema'),
        ),
    ]
