# Generated by Django 5.2.4 on 2025-07-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='codigo_cliente',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('codigo_cliente', 'sucursal', 'asesor'), name='unique_cliente_sucursal_asesor'),
        ),
    ]
