# Generated by Django 5.2.4 on 2025-07-14 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_codigo_cliente_and_more'),
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotencialDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Potencial de compra (litros)')),
            ],
            options={
                'verbose_name': 'Potencial de compra',
                'verbose_name_plural': 'Potenciales de compra',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_cliente_sucursal_asesor',
        ),
        migrations.RemoveField(
            model_name='client',
            name='potential_purchase',
        ),
        migrations.AddField(
            model_name='potencialdecompra',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potenciales', to='clients.client'),
        ),
        migrations.AddField(
            model_name='potencialdecompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potenciales', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='potencialdecompra',
            unique_together={('cliente', 'producto')},
        ),
    ]
