# Generated by Django 5.2.4 on 2025-07-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_potencialdecompra_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='asesor_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
