# Generated by Django 5.2.4 on 2025-07-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_asesor_nombre'),
        ('products', '0002_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='potencialdecompra',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='potencialdecompra',
            name='litros_empaque',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Litros por Empaque'),
        ),
        migrations.AddField(
            model_name='potencialdecompra',
            name='unidad_empaque',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad de Empaque'),
        ),
        migrations.AlterUniqueTogether(
            name='potencialdecompra',
            unique_together={('cliente', 'producto', 'unidad_empaque', 'litros_empaque')},
        ),
    ]
