# Generated by Django 5.2.4 on 2025-07-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_potencialdecompra_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='agente_retencion',
            field=models.BooleanField(default=False, verbose_name='Agente de Retención'),
        ),
        migrations.AddField(
            model_name='client',
            name='canal_venta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Canal de Venta'),
        ),
        migrations.AddField(
            model_name='client',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='client',
            name='clasificacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='client',
            name='contribuyente_especial',
            field=models.BooleanField(default=False, verbose_name='Contribuyente Especial'),
        ),
        migrations.AddField(
            model_name='client',
            name='contribuyente_iva',
            field=models.BooleanField(default=False, verbose_name='Contribuyente IVA'),
        ),
        migrations.AddField(
            model_name='client',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='client',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Contacto'),
        ),
        migrations.AddField(
            model_name='client',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='client',
            name='estatus',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='client',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='client',
            name='frecuencia_visita',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Frecuencia de Visita'),
        ),
        migrations.AddField(
            model_name='client',
            name='grupo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='client',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='client',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='client',
            name='municipio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='client',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Contacto'),
        ),
        migrations.AddField(
            model_name='client',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='client',
            name='parroquia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parroquia'),
        ),
        migrations.AddField(
            model_name='client',
            name='rif',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RIF'),
        ),
        migrations.AddField(
            model_name='client',
            name='ruta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ruta'),
        ),
        migrations.AddField(
            model_name='client',
            name='segmento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segmento'),
        ),
        migrations.AddField(
            model_name='client',
            name='subgrupo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Subgrupo'),
        ),
        migrations.AddField(
            model_name='client',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono Contacto'),
        ),
        migrations.AddField(
            model_name='client',
            name='tipo_cliente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Cliente'),
        ),
        migrations.AddField(
            model_name='client',
            name='tipo_contribuyente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Contribuyente'),
        ),
        migrations.AddField(
            model_name='client',
            name='zona_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zona Postal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='asesor_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Asesor'),
        ),
        migrations.AlterField(
            model_name='client',
            name='codigo_asesor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Asesor'),
        ),
        migrations.AlterField(
            model_name='client',
            name='codigo_cliente',
            field=models.CharField(max_length=20, verbose_name='Código Cliente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Razón Social'),
        ),
    ]
