# Generated by Django 5.2.4 on 2025-07-12 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('configuration', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del pronóstico')),
                ('tipo', models.CharField(choices=[('ventas', 'Pronóstico de Ventas'), ('demanda', 'Pronóstico de Demanda'), ('clientes', 'Pronóstico de Clientes'), ('productos', 'Pronóstico de Productos'), ('sucursal', 'Pronóstico de Sucursal')], max_length=20, verbose_name='Tipo de pronóstico')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('parametros_entrada', models.JSONField(default=dict, verbose_name='Parámetros de entrada')),
                ('resultado', models.JSONField(default=dict, verbose_name='Resultado del pronóstico')),
                ('confianza', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nivel de confianza (%)')),
                ('precision', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Precisión del modelo (%)')),
                ('fecha_inicio_forecast', models.DateField(verbose_name='Fecha inicio del pronóstico')),
                ('fecha_fin_forecast', models.DateField(verbose_name='Fecha fin del pronóstico')),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='procesando', max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True, verbose_name='Mensaje de error')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts_creados', to=settings.AUTH_USER_MODEL)),
                ('modelo_ia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_results', to='ai_models.aimodelconfig', verbose_name='Modelo de IA utilizado')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='products.product')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='clients.sucursal')),
            ],
            options={
                'verbose_name': 'Resultado de Pronóstico',
                'verbose_name_plural': 'Resultados de Pronósticos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
